// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Player struct {
	ID                               string         `json:"id"`
	FirstName                        string         `json:"firstName"`
	SecondName                       string         `json:"secondName"`
	WebName                          string         `json:"webName"`
	News                             string         `json:"news"`
	NewsAdded                        string         `json:"newsAdded"`
	Team                             string         `json:"team"`
	Position                         PlayerPosition `json:"position"`
	ChanceOfPlayingNextRound         int            `json:"chanceOfPlayingNextRound"`
	ChanceOfPlayingThisRound         int            `json:"chanceOfPlayingThisRound"`
	CostChangeEvent                  int            `json:"costChangeEvent"`
	CostChangeEventFall              int            `json:"costChangeEventFall"`
	CostChangeStart                  int            `json:"costChangeStart"`
	CostChangeStartFall              int            `json:"costChangeStartFall"`
	DreamteamCount                   int            `json:"dreamteamCount"`
	ElementType                      int            `json:"elementType"`
	EpNext                           string         `json:"epNext"`
	EpThis                           string         `json:"epThis"`
	EventPoints                      int            `json:"eventPoints"`
	Form                             string         `json:"form"`
	InDreamteam                      bool           `json:"inDreamteam"`
	NowCost                          int            `json:"nowCost"`
	Photo                            string         `json:"photo"`
	PointsPerGame                    string         `json:"pointsPerGame"`
	SelectedByPercent                string         `json:"selectedByPercent"`
	Special                          bool           `json:"special"`
	SquadNumber                      int            `json:"squadNumber"`
	Status                           string         `json:"status"`
	TeamCode                         int            `json:"teamCode"`
	TotalPoints                      int            `json:"totalPoints"`
	TransfersIn                      int            `json:"transfersIn"`
	TransfersInEvent                 int            `json:"transfersInEvent"`
	TransfersOut                     int            `json:"transfersOut"`
	TransfersOutEvent                int            `json:"transfersOutEvent"`
	ValueForm                        string         `json:"valueForm"`
	ValueSeason                      string         `json:"valueSeason"`
	Minutes                          int            `json:"minutes"`
	GoalsScored                      int            `json:"goalsScored"`
	Assists                          int            `json:"assists"`
	CleanSheets                      int            `json:"cleanSheets"`
	GoalsConceded                    int            `json:"goalsConceded"`
	OwnGoals                         int            `json:"ownGoals"`
	PenaltiesSaved                   int            `json:"penaltiesSaved"`
	PenaltiesMissed                  int            `json:"penaltiesMissed"`
	YellowCards                      int            `json:"yellowCards"`
	RedCards                         int            `json:"redCards"`
	Saves                            int            `json:"saves"`
	Bonus                            int            `json:"bonus"`
	Bps                              int            `json:"bps"`
	Influence                        string         `json:"influence"`
	Creativity                       string         `json:"creativity"`
	Threat                           string         `json:"threat"`
	IctIndex                         string         `json:"ictIndex"`
	Starts                           int            `json:"starts"`
	ExpectedGoals                    string         `json:"expectedGoals"`
	ExpectedAssists                  string         `json:"expectedAssists"`
	ExpectedGoalInvolvements         string         `json:"expectedGoalInvolvements"`
	ExpectedGoalsConceded            string         `json:"expectedGoalsConceded"`
	InfluenceRank                    int            `json:"influenceRank"`
	InfluenceRankType                int            `json:"influenceRankType"`
	CreativityRank                   int            `json:"creativityRank"`
	CreativityRankType               int            `json:"creativityRankType"`
	ThreatRank                       int            `json:"threatRank"`
	ThreatRankType                   int            `json:"threatRankType"`
	IctIndexRank                     int            `json:"ictIndexRank"`
	IctIndexRankType                 int            `json:"ictIndexRankType"`
	CornersAndIndirectFreekicksOrder int            `json:"cornersAndIndirectFreekicksOrder"`
	CornersAndIndirectFreekicksText  string         `json:"cornersAndIndirectFreekicksText"`
	DirectFreekicksOrder             int            `json:"directFreekicksOrder"`
	DirectFreekicksText              string         `json:"directFreekicksText"`
	PenaltiesOrder                   int            `json:"penaltiesOrder"`
	PenaltiesText                    string         `json:"penaltiesText"`
	ExpectedGoalsPer90               float64        `json:"expectedGoalsPer90"`
	SavesPer90                       float64        `json:"savesPer90"`
	ExpectedAssistsPer90             float64        `json:"expectedAssistsPer90"`
	ExpectedGoalInvolvementsPer90    float64        `json:"expectedGoalInvolvementsPer90"`
	ExpectedGoalsConcededPer90       float64        `json:"expectedGoalsConcededPer90"`
	GoalsConcededPer90               float64        `json:"goalsConcededPer90"`
	NowCostRank                      int            `json:"nowCostRank"`
	NowCostRankType                  int            `json:"nowCostRankType"`
	FormRank                         int            `json:"formRank"`
	FormRankType                     int            `json:"formRankType"`
	PointsPerGameRank                int            `json:"pointsPerGameRank"`
	PointsPerGameRankType            int            `json:"pointsPerGameRankType"`
	SelectedRank                     int            `json:"selectedRank"`
	SelectedRankType                 int            `json:"selectedRankType"`
	StartsPer90                      float64        `json:"startsPer90"`
	CleanSheetsPer90                 float64        `json:"cleanSheetsPer90"`
}

type Query struct {
}

type Team struct {
	ID                  string `json:"id"`
	Name                string `json:"name"`
	ShortName           string `json:"shortName"`
	StrengthOverallHome int    `json:"strengthOverallHome"`
	StrengthOverallAway int    `json:"strengthOverallAway"`
	StrengthAttackHome  int    `json:"strengthAttackHome"`
	StrengthAttackAway  int    `json:"strengthAttackAway"`
	StrengthDefenceHome int    `json:"strengthDefenceHome"`
	StrengthDefenceAway int    `json:"strengthDefenceAway"`
}

type PlayerPosition string

const (
	PlayerPositionGkp PlayerPosition = "GKP"
	PlayerPositionDef PlayerPosition = "DEF"
	PlayerPositionMid PlayerPosition = "MID"
	PlayerPositionFwd PlayerPosition = "FWD"
)

var AllPlayerPosition = []PlayerPosition{
	PlayerPositionGkp,
	PlayerPositionDef,
	PlayerPositionMid,
	PlayerPositionFwd,
}

func (e PlayerPosition) IsValid() bool {
	switch e {
	case PlayerPositionGkp, PlayerPositionDef, PlayerPositionMid, PlayerPositionFwd:
		return true
	}
	return false
}

func (e PlayerPosition) String() string {
	return string(e)
}

func (e *PlayerPosition) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlayerPosition(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlayerPosition", str)
	}
	return nil
}

func (e PlayerPosition) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
